### ISSUE TITLE
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [信号灯超时时间已到]

### ISSUE THREAD

**Issue by chenzhizhuan** [say8hi/websocket-chat#1]
(agti) PS C:\Users\Administrator\Desktop\AGTiSpace\AGTi-Backend\tg_bot> python bot.py
2024-11-14 01:18:55,247 INFO     [__main__] (bot.py:setup_logging:36) Starting bot
Config(tg_bot=TgBot(token='7672011778:AAEDPTVzLnREnGYxpat3k57IIfFZT3s90eE', admins=[6101041887]))
<aiogram.client.bot.Bot object at 0x000002B50FC967D0>
2024-11-14 01:18:55,670 INFO     [aiogram.dispatcher] (dispatcher.py:start_polling:527) Start polling
2024-11-14 01:19:16,747 INFO     [aiogram.dispatcher] (dispatcher.py:start_polling:554) Polling stopped
HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [信号灯超时时间已到]
(agti) PS C:\Users\Administrator\Desktop\AGTiSpace\AGTi-Backend\tg_bot> python bot.py
2024-11-14 01:19:54,314 INFO     [__main__] (bot.py:setup_logging:34) Starting bot
2024-11-14 01:19:54,784 INFO     [aiogram.dispatcher] (dispatcher.py:start_polling:527) Start polling
2024-11-14 01:20:15,850 INFO     [aiogram.dispatcher] (dispatcher.py:start_polling:554) Polling stopped
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohappyeyeballs\impl.py", line 104, in start_connection
    raise first_exception
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohappyeyeballs\impl.py", line 82, in start_connection
    sock = await _connect_sock(
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohappyeyeballs\impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "C:\Users\Administrator\.conda\envs\agti\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\Administrator\.conda\envs\agti\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\.conda\envs\agti\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\session\aiohttp.py", line 181, in make_request
    async with session.post(
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\client.py", line 663, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiohttp\connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [信号灯超时时间已到]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\AGTiSpace\AGTi-Backend\tg_bot\bot.py", line 58, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\.conda\envs\agti\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\.conda\envs\agti\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\AGTiSpace\AGTi-Backend\tg_bot\bot.py", line 53, in main
    await dp.start_polling(bot)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 551, in start_polling
    await asyncio.gather(*done)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 340, in _polling
    user: User = await bot.me()
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\bot.py", line 359, in me
    self._me = await self.get_me()
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\bot.py", line 1851, in get_me
    return await self(call, request_timeout=request_timeout)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\Administrator\.conda\envs\agti\lib\site-packages\aiogram\client\session\aiohttp.py", line 188, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [信号灯超时时间已到]

**Comment by chenzhizhuan** [comment]
(agti) PS C:\Users\Administrator\Desktop\AGTiSpace\AGTi-Backend\tg_bot> pip list
Package              Version
-------------------- -----------
aiofiles             23.2.1
aiogram              3.11.0
aiohappyeyeballs     2.3.5
aiohttp              3.10.10
aioredis             2.0.1
aiosignal            1.3.1
alembic              1.13.1
amqp                 5.2.0
aniso8601            9.0.1
annotated-types      0.6.0
anyio                4.3.0
ariadne              0.22
async-timeout        4.0.3
asyncpg              0.29.0
attrs                24.2.0
bcrypt               4.0.1
betterlogging        1.0.0
billiard             4.2.1
celery               5.4.0
certifi              2024.2.2
cffi                 1.17.1
charset-normalizer   3.4.0
click                8.1.7
click-didyoumean     0.3.1
click-plugins        1.1.1
click-repl           0.3.0
colorama             0.4.6
cryptography         43.0.3
dnspython            2.6.1
email-validator      2.1.0.post1
environs             11.0.0
exceptiongroup       1.2.2
fastapi              0.109.2
fastapi-cache2       0.2.2
frozenlist           1.4.1
graphene             3.3
graphql-core         3.2.3
graphql-relay        3.2.0
greenlet             3.0.3
grpcio               1.62.0
h11                  0.14.0
httpcore             1.0.4
httptools            0.6.1
httpx                0.27.0
idna                 3.6
iniconfig            2.0.0
itsdangerous         2.1.2
Jinja2               3.1.3
kombu                5.4.2
magic-filter         1.0.12
Mako                 1.3.2
MarkupSafe           2.1.5
marshmallow          3.21.3
multidict            6.0.5
nodeenv              1.9.1
orjson               3.9.14
packaging            23.2
passlib              1.7.4
pendulum             3.0.0
pillow               10.4.0
pip                  24.2
pluggy               1.4.0
prompt_toolkit       3.0.48
propcache            0.2.0
pyaes                1.6.1
pyasn1               0.6.0
pycparser            2.22
pydantic             2.6.1
pydantic_core        2.16.2
pydantic-extra-types 2.5.0
pydantic-settings    2.2.1
PyJWT                2.9.0
pyright              1.1.377
pytest               8.0.1
pytest-asyncio       0.23.5
python-dateutil      2.9.0.post0
python-dotenv        1.0.1
python-multipart     0.0.9
pytz                 2024.1
PyYAML               6.0.1
redis                5.1.1
requests             2.32.3
rsa                  4.9
setuptools           75.1.0
six                  1.16.0
sniffio              1.3.0
SQLAlchemy           2.0.27
starlette            0.36.3
Telethon             1.36.0
time-machine         2.16.0
tomli                2.1.0
typing_extensions    4.12.2
tzdata               2024.2
tzlocal              5.2
ujson                5.9.0
urllib3              2.2.3
uvicorn              0.27.1
vine                 5.1.0
watchfiles           0.21.0
wcwidth              0.2.13
websockets           12.0
wheel                0.44.0
yarl                 1.17.1

**Comment by chenzhizhuan** [comment]
My network is functioning normally, the Bot Token is also entered correctly, and the bot can operate normally using other methods.
